### ISSUE TITLE
utm_geo() routines needs correction

### ISSUE THREAD

**Issue by danielpeter** [SCECcode/cvms5#1]
Please note that your utm_geo() routine provided to convert long/lat to UTM coordinates contains two 2 mistakes:

source file: utm_geo.f90

line 95:
https://github.com/SCECcode/cvms5/blob/0635765ae80312e2e0aa168fe28d6d68d83c925a/src/utm_geo.f90#L95

wrong: `f3=15.d0*e4/256.d0*45.d0*e6/1024.d0`
correct would be: `f3=15.d0*e4/256.d0 + 45.d0*e6/1024.d0`

line 160:
https://github.com/SCECcode/cvms5/blob/0635765ae80312e2e0aa168fe28d6d68d83c925a/src/utm_geo.f90#L160

wrong:  `f3=5.d0*3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2`
correct would be:  `f3=5.d0 + 3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2`

the above corrections could be verified by looking at the original publication:
Snyder, J.P., Map projections - a working manual, USGS professional paper 1395, 1987
https://doi.org/10.3133/pp1395

line 95 mistake/correction: see page 61, eq. 3-21 for M
line 160 mistake/correction: see page 63, eq. 8-17 for phi

the above error will lead to a positional error of ~7 m when converting lon/lat to UTM.

best regards,
daniel

**Comment by meihuisu** [comment]
Thank you so much for finding these errors. We will correct them in all the models that are dependent on this function.

mei
________________________________
From: daniel peter ***@***.***>
Sent: Tuesday, May 4, 2021 1:18 AM
To: SCECcode/cvms5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SCECcode/cvms5] utm_geo() routines needs correction (#1)


Please note that your utm_geo() routine provided to convert long/lat to UTM coordinates contains two 2 mistakes:

source file: utm_geo.f90

line 95:
https://github.com/SCECcode/cvms5/blob/0635765ae80312e2e0aa168fe28d6d68d83c925a/src/utm_geo.f90#L95<https://urldefense.com/v3/__https://github.com/SCECcode/cvms5/blob/0635765ae80312e2e0aa168fe28d6d68d83c925a/src/utm_geo.f90*L95__;Iw!!LIr3w8kk_Xxm!_0pbGo5ZoRwHm9ZHlqpDKjzl6kAC-I-JddrBPxMbZrQAPsLWGc-NYDUfbuM$>

wrong: f3=15.d0*e4/256.d0*45.d0*e6/1024.d0
correct would be: f3=15.d0*e4/256.d0 + 45.d0*e6/1024.d0

line 160:
https://github.com/SCECcode/cvms5/blob/0635765ae80312e2e0aa168fe28d6d68d83c925a/src/utm_geo.f90#L160<https://urldefense.com/v3/__https://github.com/SCECcode/cvms5/blob/0635765ae80312e2e0aa168fe28d6d68d83c925a/src/utm_geo.f90*L160__;Iw!!LIr3w8kk_Xxm!_0pbGo5ZoRwHm9ZHlqpDKjzl6kAC-I-JddrBPxMbZrQAPsLWGc-NciUeBcU$>

wrong: f3=5.d0*3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2
correct would be: f3=5.d0 + 3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2

the above corrections could be verified by looking at the original publication:
Snyder, J.P., Map projections - a working manual, USGS professional paper 1395, 1987
https://doi.org/10.3133/pp1395<https://urldefense.com/v3/__https://doi.org/10.3133/pp1395__;!!LIr3w8kk_Xxm!_0pbGo5ZoRwHm9ZHlqpDKjzl6kAC-I-JddrBPxMbZrQAPsLWGc-NtC1IXgo$>

line 95 mistake/correction: see page 61, eq. 3-21 for M
line 160 mistake/correction: see page 63, eq. 8-17 for phi

the above error will lead to a positional error of ~7 m when converting lon/lat to UTM.

best regards,
daniel

**Comment by meihuisu** [comment]
Hi,

  I have committed the changes into the latest UCVM target.  This is a new
streamlined UCVM core code (minus the original plotting scripts which are in
a separate package bundle now)

thanks again for the bug report.
________________________________
